### ISSUE TITLE
Set calibration factor vor voltage and current

### ISSUE THREAD

**Issue by raohamza888** [voelkerb/STPM3X#4]
Hello, I am attempting to understand how you set the values inside this function. I don't understand it, and I've looked through the library files STPM3X.h and .cpp, but I couldn't find any relevant information. Could you please help me clarify this? I would greatly appreciate it. Thank you!
// stpm3x.setCalibration(1.01, 1.1);

**Comment by voelkerb** [comment]
Hey. [`setCalibration(float calV, float calI)`](https://github.com/voelkerb/STPM3X/blob/55c8c50895c0c0480d0d1f6ae93bef8f8d28a64c/src/STPM3X.cpp#L207) sets a member variable (calibration vector) inside the library. This is simply multiplied with all current/voltage measurements, simplified written as: 
```C
float volt = convert2Volt(rawVolt) * calV;
float current = convert2Cur(rawCur) * calI;
```
You can use this if e.g. your voltage dividers are designed differently or some component deviations prevent that you perfectly measure the real value. I.e. if your output is `200V` but you measured it with laboratory equipment and it should be `230V`, set `calV` to `230.0/200.0=1.15`.

**Comment by voelkerb** [comment]
Does it answer your question? If so, I will close this issue and add the calibration section to the README.

**Comment by raohamza888** [comment]
Great! Yes, you can close this issue. Thank you so much for the help.
