### ISSUE TITLE
Reading Out Active and Reactive energy pulse

### ISSUE THREAD

**Issue by aaltonen1024** [voelkerb/STPM3X#5]
Hi, is there a way to configure the Energy pulses as an output so that I can read it on an oscilloscope? I've read in the datasheet that there are 2 pins (`LED1` and `LED2`) which are primary and secondary channel energies. How can I implement this in, let's say, the example code?

**Comment by voelkerb** [comment]
Sure this can be implemented in the library. The behaviour of the LED1 and 2 pins can be configured in `DSP_CR1` and `DSP_CR3`, respectively (pulse speed, pulse output power (active, reactive fundamental, apparent), channel etc. The corresponding settings can be found in the [data-sheet](https://www.st.com/resource/en/datasheet/stpm32.pdf) at page 62ff.
Feel free to implement it as part of the library.
